# Generated by Django 2.1.7 on 2020-05-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='liked_count',
            new_name='liked_num',
        ),
    ]
